cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask'

# install packages
brew 'fish'
brew 'node'
brew 'gtop'
brew 'mas'
brew 'neofetch'
brew 'tree'
brew 'wget'
brew 'yarn'
brew 'pyenv'
# required for manim
brew 'py3cairo'
brew 'ffmpeg'

# install casks
cask 'spotify'
cask 'visual-studio-code'
cask 'alacritty'
cask 'miktex-console'
cask 'raycast'
cask 'logi-options-plus'
cask 'obs'
cask 'julia'

# install apps from App Store
# mas 'AdGuard for Safari', id: 1440147259
# mas 'Noir', id: 1592917505
