[colors.bright]
black   = "#666666"
blue    = "#A1BDFF"
cyan    = "#A1BDFF"
green   = "#A1BDFF"
magenta = "#D66E86"
red     = "#D66E86"
white   = "#DFDFDF"
yellow  = "#997CD5"

[colors.normal]
black   = "#000000"
blue    = "#A1BDFF"
cyan    = "#A1BDFF"
green   = "#A1BDFF"
magenta = "#D66E86"
red     = "#D66E86"
white   = "#DFDFDF"
yellow  = "#997CD5"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 12

[font.normal]
family = "MesloLGS NF"
style  = "Regular"

[font.bold]
family = "MesloLGS NF"
style  = "Bold"

[font.italic]
family = "MesloLGS NF"
style  = "Italic"

[font.bold_italic]
family = "MesloLGS NF"
style  = "Bold Italic"

[window]
padding         = { x = 20, y = 20 }
decorations     = "Buttonless"
dynamic_padding = true
opacity         = 0.6
blur            = true
title           = "Terminal"

[bell]
duration = 200
color    = "#000000"